const USER_ACTION_TYPES = {
  FETCH_CURRENT_USER_START: "FETCH_CURRENT_USER_START",
  FETCH_CURRENT_USER_SUCCESS: "FETCH_CURRENT_USER_SUCCESS",
  FETCH_CURRENT_USER_FAILED: "FETCH_CURRENT_USER_FAILED",
};

export default USER_ACTION_TYPES;
